### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by lukynmatuska** [RichardKlem/ITY#1]
There is always option to get information about your study in WIS (IS FIT BUT).

WIS is not completely dead.
1. Go to [WIS homepage](https://wis.fit.vutbr.cz/) and login with your (student) credentials
![Screenshot_20230417_231215](https://user-images.githubusercontent.com/19732513/232704810-93fd703c-6b77-4566-bf56-8d0e4f9bd12f.png)
2. Open list of studies
![Screenshot_20230417_231226](https://user-images.githubusercontent.com/19732513/232704962-f6e6e1e7-6bee-4984-adfe-a22a80ef3db6.png)
3. Select study
![Screenshot_20230417_231251](https://user-images.githubusercontent.com/19732513/232705500-2c15ebc8-183d-4b68-81f2-18455d9a3579.png)
4. Enjoy our old good WIS. 🫀

**Comment by RichardKlem** [comment]
Solved by [aa422af](https://github.com/RichardKlem/ITY/commit/aa422af2f019c78e3d2b841bbb0b89944bd68493).
